services:
  db:
    image: postgres:15
    container_name: todo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    
  docs:
    image: squidfunk/mkdocs-material
    container_name: todo_docs
    ports:
      - "8001:8000"
    volumes:
      - ./docs:/docs
      - ./mkdocs.yml:/mkdocs.yml
    working_dir: /
    command: serve --dev-addr=0.0.0.0:8000


volumes:
  pgdata:
